### ISSUE TITLE
Failed TCP connections can give false beacon results

### ISSUE THREAD

**Issue by ethack** [activecm/rita#117]
Failed TCP connections can cause new connections to happen on the same second. This appears as a beacon with a delta time of 1.

Suggest using the "state" field in the bro logs to exclude any failed connections and only use successful ones.

Note: strictly speaking, malware could hide data in TCP packets that don't go through the 3-way handshake and this would not be detected.

**Comment by Zalgo2462** [comment]
In addition to failed connections triggering the beaconing algorithm, some computers simply create tcp sessions at a rate greater than once a second. RITA currently uses integral seconds to store timestamps. RITA must move to some sort of fractional seconds in order to fix this issue.

**Comment by Zalgo2462** [comment]
One way to detect failed TCP connections would be to look at the number of packets sent. 3 packets make a TCP session. No less.

**Comment by Zalgo2462** [comment]
Needed to do some filtering to tell if IPFIX-RITA was working correctly. The sample packet capture I'm using has a lot of tcp scan data which was getting in the way. Unfortunately, I couldn't find a capture of similar size to work with without the noise. [Using MACCDC packet captures]

The patch is there, but the tests aren't written.
