### ISSUE TITLE
RITA Drops Connections Which Persist Across Dates When UseDates Is Configured

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/rita#133]
Bro IDS timestamps signify the start of the recorded event. However, Bro writes the event when the event has finished. A connection which opens at 23:58 on day 1 may persist until 00:04 on day 2. Bro will write the event to day 2's dataset with a timestamp recorded on day 1.

RITA uses timestamps to determine which dataset to import a record into. If the dataset for day 1 has already been parsed and analyzed, RITA will not insert the problem connection to the analyzed dataset., nor will it be inserted into day 2's dataset. RITA will log this with an error. 

Is there a better solution?

**Comment by ethack** [comment]
We're deprecating the `UseDates` function.  We will remove it in favor of other solutions: possibly a separate script or even an import/analyze methodology that achieves the same result along with Bro's daily log rotation.
