### ISSUE TITLE
RITA system requirements.

### ISSUE THREAD

**Issue by rolfnufable** [activecm/rita#139]
I tried to look for available RITA forums but didn't find anything , So i'll just ask here..

We would like to deploy/ install rita on our network. 

Just minor questions for now.

What are the system requirements for the deployment of RITA to be optimal? ( from What I see it needs a lot of hard disk space since BRO and RITA would eat a lot of it while running live ) .

But how about other specs like RAM? , etc. We're also looking for future issues for scalability.

What I've thought so far for Automating the process of analyzing the bro logs using rita is to use a cronjob to automate the rita command to analyze, while Bro's logging rotation is set to lets say 1 day.
( is there a better option to automate rita? , this is for analyzing live traffic).

TIA for the help !

**Comment by ethack** [comment]
It highly depends on your actual bandwidth.  The higher your bandwidth, the more data you'll produce which will take more resources both to capture (Bro) and later analyze (RITA).

Figuring out some optimal specs is on our list of things to do.  We would certainly appreciate community-contributed data points (hint hint to anyone reading this :-)).  For now, I've been pointing people to the [Hardware page](https://github.com/Security-Onion-Solutions/security-onion/wiki/Hardware) on Security Onion's wiki for guidelines.  That at least gets you started with spec'ing out for Bro.  I can tell you RITA is memory intensive and will use what you throw at it, especially running alongside Mongo.  For instance, I've recently been analyzing 20GB datasets and I think it usually sits around 35-45GB RAM usage.  Though there was a time when all 96GB of RAM was been maxed out and plus another 40GB of swap.  That may have been an anomaly though. 

A cronjob is the best option we've come up with as well.

**Comment by meljbruno** [comment]
Closing issue, as a link to the answer was posted.
