### ISSUE TITLE
Allow RITA to perform selected analyses/ allow developers add analysis modules easily

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/rita#141]
In order to add an analysis module, a developer must create a new analysis module and hard code the new routine in to the analyse command. Additionally, users must run every single analysis coded into RITA. 

In theory, we could add a module system to the analysis package. By listing the dependencies of each analysis module, RITA could dynamically generate a plan of execution. Additionally, users could list what analyses they would like to run, and RITA could generate a proper analysis.

We would need an object to represent each analysis module. Additionally, we will need to be able to reference these objects between modules. Wrapping each module in an object and providing singleton constructors should allow for this. From there we can use [Kahn's algorithm](http://www.geeksforgeeks.org/topological-sorting-indegree-based-solution/) to topologically sort the modules and generate a plan of execution.

**Comment by ethack** [comment]
There is currently a research effort that would supersede this issue. Do not work on this issue until further notice.

**Comment by ethack** [comment]
https://github.com/activecm/rita/issues/266 is at least related and could possibly close this issue as well.
