### ISSUE TITLE
Beacon analysis based on domains

### ISSUE THREAD

**Issue by ethack** [activecm/rita#143]
Track beaconing behavior from internal IP addresses to domains.  This would help catch malware that is using [fast flux techniques](https://en.wikipedia.org/wiki/Fast_flux).

**Comment by Zalgo2462** [comment]
We could also look at one-to-many beaconing rather than our current approach of one-to-one.

**Comment by ethack** [comment]
Duplicate of https://github.com/activecm/rita/issues/603
