### ISSUE TITLE
Add support for Bro logs in JSON format

### ISSUE THREAD

**Issue by tkinkead** [activecm/rita#146]
We log Bro files directly into JSON format for easier downstream parsing by logstash.  Add a parser to import bro logs that are logged natively in JSON format.

**Comment by monkykap** [comment]
I second this feature request 👍. We do this as well.

**Comment by ethack** [comment]
Good suggestion.  We're currently working on a Bro plugin that will allow logging to Mongodb directly from Bro (#70).  This should allow you to ingest from Bro no matter what format your log files are.

**Comment by ethack** [comment]
Another option slated for research is this logstash plugin:
https://www.elastic.co/guide/en/logstash/current/plugins-outputs-mongodb.html

**Comment by arnydo** [comment]
+1 for this feature. Would like to be able to run Rita alongside Security Onion but can't import he Bro logs as-is.

**Comment by jsdjjsd** [comment]
Definitely a +1 here. Currently running on Security Onion and am having to prioritise either running Elasticsearch or RITA, would love to be able to do both with JSON.

**Comment by kpsmiley23** [comment]
+1 As I'm also trying to use BRO logs from Security Onion so I'm wondering if there any JSON to TSV scripts already available that anyone knows of or created themselves?  I'm trying to write something to convert them as I don't want to stay with JSON for the time being...

**Comment by herdingcatz** [comment]
This might work, or not..
http://hackage.haskell.org/package/jsontsv

**Comment by weslambert** [comment]
You can also switch to TSV logs in Security Onion, like so:

https://securityonion.readthedocs.io/en/latest/bro.html#tsv

Thanks,
Wes

**Comment by Ucnt** [comment]
Anyone found JSON to TSV parsers?  If not, I'm standing up a second security onion box to look at doing it for conn, dns, http and ssl.

**Comment by Ucnt** [comment]
I just finished writing a python parser (faster than to do it in go, which is my aim so I can do a PR).  If anyone is interested in testing it out, please let me know (profile links to multiple contacts methods, e.g. LinedIn).   

I successfully converted all 4 logs types to TSV and imported them into Rita.  Only "negative" is that TSV files have an "xopen [date]" line that isn't really feasible to add.  Hopefully that's not used by Rita (need to look at the code).

**Comment by ethack** [comment]
That's wonderful! If you're talking about the `#open` line in the TSV header we don't use that.

**Comment by Ucnt** [comment]
Nice!  Thanks for the response.  I know it's not a final solution but I'll post the code on GitHub once vetted/commented then see if a PR makes sense  (not sure the best way to try to get the capability into Rita, e.g. JSON->TSV->import or a new parser-> struct implementation).

**Comment by Ucnt** [comment]
For those interested, this is the converter I created, specifically to work with logs for Rita, not all Bro logs.

https://github.com/Ucnt/bro-json-to-tsv

I have been running it at work for a week and have not seen any issues.

Still hope to get cycles to do it in Go.

**Comment by ethack** [comment]
@Ucnt thank you for sharing! Would you mind if we put a link to your project in our documentation?

As far as converting to Go, I'd suggest holding off. Our importer right now is very coupled with parsing the TSV files and I think it would be difficult to add in the JSON parser. We have some ideas of decoupling this in the future that would make adding in other parsers much easier. I don't have an ETA right now on that.

**Comment by Ucnt** [comment]
More than happy to have the link shared.  Hopefully it can help others.
I'll double back and be sure documentation is straight forward, etc.

Sounds good on converting and makes total sense.

**Comment by Ucnt** [comment]
Before I deprecate https://github.com/Ucnt/bro-json-to-tsv, does a README update need to be done, e.g. to indicate there is no need to switch Security Onion to TSV output?

**Comment by ethack** [comment]
Great point. I forgot to modify the documentation. I'll need to make a pull request to Security Onion's docs too. Thanks for the reminder!
