### ISSUE TITLE
Can I import firewall/proxy data from Splunk into RITA?

### ISSUE THREAD

**Issue by dfir-dave** [activecm/rita#161]
Can I export firewall/proxy logs from Splunk in csv format and then import the data into RITA for analysis? What column names is RITA expecting when I use the import function? Thanks in advance

**Comment by ethack** [comment]
The only currently supported import method is using Bro logs.  The analysis used is pretty heavily reliant on the information from Bro so it's unlikely to be able to work with other log sources.  This is an idea we occasionally discuss and revisit, but it's not on our list right now.

**Comment by ethack** [comment]
I wanted to give an update here before closing this as an old issue.  We are currently in the process of supporting IPFix as an input source for RITA which should allow many firewalls to directly interface.
https://github.com/activecm/ipfix-rita
