### ISSUE TITLE
Not working:  Option 2 for repeated imports from Bro into Mongo 

### ISSUE THREAD

**Issue by jostromzyston** [activecm/rita#170]
I have rita deployment running just fine with one time import (-i).  However, we can't get it to continuously import bro logs into mongodb (option 2 for repeated imports).  Anyone dealt with this before?  Could anyone help me on what to troubleshoot?  Can't see an update interval that is set, and I don't see anything in the logs.
This is from Readme:
"Option 2: Set up the Bro configuration in config.yaml for repeated imports"
Running Rita version:
rita version v1.0.0-alpha2-11-ga59124b

**Comment by Zalgo2462** [comment]
Hello, thanks for your feedback!
Could you please post the results of `rita test-config`? Be sure to remove your google API key if you have set up the blacklisted module. 

I have a theory that the UseDates option may be causing an issue.

**Comment by jostromzyston** [comment]
Here is the output from `rita test-config`.  Appreciate the help.
user@host:~$ rita test-config

BatchSize: 300
DatabaseHost: localhost:27017
Prefetch: 0.33
LogConfig:
  LogLevel: 2
  RitaLogPath: /home/user/.rita/logs
  LogToFile: true
  RitaLogTable: logs
  LogToDB: true
BlackListed:
  ThreadCount: 2
  ChannelSize: 1000
  BlackListTable: blacklisted
  Database: rita-blacklist
Dns:
  ExplodedDnsTable: explodedDns
  HostnamesTable: hostnames
Crossref:
  InternalTable: internXREF
  ExternalTable: externXREF
  BeaconThreshold: 0.7
Scanning:
  ScanThreshold: 50
  ScanTable: scan
Structure:
  ConnectionTable: conn
  HttpTable: http
  DnsTable: dns
  UniqueConnectionTable: uconn
  HostTable: host
Beacon:
  DefaultConnectionThresh: 24
  BeaconTable: beacon
Urls:
  UrlsTable: urls
UserAgent:
  UserAgentTable: useragent
Bro:
  LogPath: /nsm/bro/logs/current
  DBPrefix: PrefixForDatabase
  MetaDB: MetaDatabase
  DirectoryMap:
    UniqueDir: SeparateDatabaseName
    UniqueDir2: SeparateDatabaseName2
  DefaultDatabase: ""
  UseDates: false
  ImportBuffer: 100000
SafeBrowsing:
  APIKey: ""
  Database: /home/user/.rita/safebrowsing
MetaTables:
  FilesTable: files
  DatabasesTable: databases
version: v1.0.0-alpha2-15-gddfdd1c

**Comment by Zalgo2462** [comment]
It looks like your directory map isn't being set up correctly. Could you please post your ~/.rita/config.yaml?

**Comment by jostromzyston** [comment]
Sure, here you go.  I just used all defaults.  What controls how often the bro logs are automatically imported?  Beyond turning on the feature to automatically import, I can't see where the timing is defined.  Thanks.
user@host:~/.rita$ cat config.yaml
# Mongo Database to connect to
DatabaseHost: localhost:27017

LogConfig:
    # LogLevel
    # 3 = debug
    # 2 = info
    # 1 = warn
    # 0 = error
    LogLevel: 2

    # LogPath is the path for Rita's logs, generally this just defaults to
    # $HOME/.rita/logs. Logs will only be written here if LogToFile is true
    RitaLogPath: $HOME/.rita/logs
    LogToFile: true

    RitaLogTable: logs
    LogToDB: true

# The section Bro configures the bro ingestor
Bro:
    # Path to a top level directory of log files
    LogPath: /nsm/bro/logs/current

    # All databases in this test will get prefixed with the database prefix
    DBPrefix: PrefixForDatabase

    # Subdirectories of LogPath may be separated into different databases for the
    # test. Map each directory to the database you wish that directory to wind up
    # in. This is good for running tests against multiple subnets and network
    # segments. Put the directory name on the left side of the colon, and the
    # database you wish the logs from that directory to go in on the right side.
    DirectoryMap:
        UniqueDir: SeparateDatabaseName
        UniqueDir2: SeparateDatabaseName2

    # If set, files which don't match the directory map will be placed
    # in this default database.
    #DefaultDatabase: DefaultDatabaseName

    # There needs to be one metadatabase per test. This database holds information
    # about the test and the files related to the test. If there are several
    # subnets mapped in DirectoryMap each will be handled separately and that
    # separation is handled by the metadatabase.
    MetaDB: MetaDatabase

    # If use dates is true the logs will be split into databases by date, this is
    # best for if you have multiple days worth of log files in the logpath and wish
    # to treat each day as a separate test. 24hours worth of data is the ideal for
    # analysis, and using dates will ensure that tests are broken into 24hour periods
    # around midnight of each day.
    UseDates: false

    # The number of records shipped off to MongoDB at a time. Increasing
    # the size of the buffer will improve import timings but will leave more
    # records unimported if there is an error
    ImportBuffer: 100000

SafeBrowsing:
    APIKey: ""
    Database: $HOME/.rita/safebrowsing

# NOTE: DO NOT CHANGE THE SETTINGS BELOW UNLESS YOU ARE FAMILIAR WITH THE CODE #
Structure:
    ConnectionTable: conn
    HttpTable: http
    DnsTable: dns
    UniqueConnectionTable: uconn
    HostTable: host

BlackListed:
    ThreadCount: 2
    ChannelSize: 1000
    BlackListTable: blacklisted
    Database: rita-blacklist

Dns:
    ExplodedDnsTable: explodedDns
    HostnamesTable: hostnames

Crossref:
    InternalTable: internXREF
    ExternalTable: externXREF
    BeaconThreshold: .7

Scanning:
    ScanThreshold: 50
    ScanTable: scan

Beacon:
    DefaultConnectionThresh: 24
    BeaconTable: beacon

Urls:
    UrlsTable: urls

UserAgent:
    UserAgentTable: useragent

MetaTables:
    FilesTable: files
    DatabasesTable: databases


# Adjusting batchsize and prefetch may help speed up certain database queries
BatchSize: 300
Prefetch: 0.33
user@host:~/.rita$

**Comment by ethack** [comment]
There's not a very good way to run RITA automatically at a defined period.  You can put together a solution involving setting "UseDates" in your config file and then creating a cron entry to run RITA every night.

Just know that "UseDates" will be going away, or at the very least changing significantly, in the next release.  We're trying to find a better solution to have RITA be run automatically.

For now, I'd recommend doing something like this in a cron set to run after 12:30am each night (to ensure Bro has rotated its logs already).

```
rita import -i /nsm/bro/logs/$(date +%Y-%m-%d) -d $(date +%Y-%m-%d) && rita analyze
```

That assumes you have Bro rotating logs daily and the folder names look like `/nsm/bro/logs/2018-02-02`.

**Comment by ethack** [comment]
Versions 1.0.0 and 1.0.1 of RITA include the ability to just run `rita import` and it will pull any new log folders that haven't already been processed.  This should address this issue.
