### ISSUE TITLE
Automate the configuration of RITA

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/rita#174]
The install script currently builds and installs RITA; however it is unconfigured at the end of the script. This configuration step should be automated (connecting Mongo, setting the import directory, directing the user to get a google API key)

**Comment by ethack** [comment]
I'm closing this issue as the default configuration is now a working configuration.  There could still be the possibility to script configuring the Google API key or allow customizing the configuration.  However, I don't believe those to be worth the effort right now.
