### ISSUE TITLE
Automate the configuration of Bro IDS in the installer

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/rita#175]
In order to make the installation of RITA more seamless, the RITA install script should offer the option to configure Bro.

**Comment by ethack** [comment]
This is a script that automates a clustered config. I'm not sure it will be helpful here, but I just wanted you to know it exists.

https://github.com/ocmdev/bro-install/blob/master/gen-node-cfg.sh

**Comment by ethack** [comment]
Closed with https://github.com/activecm/rita/pull/245
