### ISSUE TITLE
Go installation creates separate GOPATHs. (Odd Go Installation)

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/rita#190]
In the rita installer, go is installed to /usr/local/go if it is not detected. Currently a GOPATH is created in /opt/rita, and, for the duration of the script, this directory is set to the $GOPATH environment variable. However, this environment variable is not added to the user's bashrc file as /opt/rita is not writable without administrator privileges. Despite this, /usr/local/go is added to the user's PATH variable in their bashrc. This means when a user runs go, the default GOPATH at $HOME/go is created. This GOPATH is divorced from the one used to install rita.

Administrator level GOPATH's aren't supported very well by go. Especially as sudo strips most environment variables. 

We can solve this problem in one of two ways while still providing a system wide installation.

Solution A: Make the GOPATH writable by everyone. This removes the need for sudo. However, this prevents using go in the traditional sense (one GOPATH per user). If we go this route, we may want to move the GOPATH to a place other than /opt/rita as setting the GOPATH to will create executables in /opt/rita/bin unrelated to RITA.

Solution B: Use the user's GOPATH and copy the built executable to the system wide location. This is more akin to standard "make install" programs.

I prefer solution B as it follows more industry standards than solution A.

**Comment by Zalgo2462** [comment]
In lieu of #194 solution B is less attractive.

I'm still not a fan of Solution A however.

@ethack proposed another solution (Solution C): Building RITA in a docker container. This would provide reproducible builds and we wouldn't have to muck with GOPATHs at all. Additionally, RITA already has a functioning Dockerfile. However, that may pose its own issues (mainly around linking).

**Comment by ethack** [comment]
Fixed with #197
