### ISSUE TITLE
RITA Installer Does Not Follow the Filesystem Hierarchy Standard

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/rita#191]
The [Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) is a standard defined by the Linux Foundation as guidance on how to organize files on UNIX-like systems. 

If RITA were to follow the FHS, several files would need to be moved.

Assuming an opt install.
```
GOPATH/bin/rita [the executable] -> /opt/rita/bin/rita
LICENSE -> /opt/rita/LICENSE
config.yaml -> /etc/opt/rita/config.yaml
tables.yaml -> /etc/opt/rita/tables.yaml
safebrowsing -> /var/opt/rita/lib/safebrowsing
RITALogPath -> /var/opt/rita/log/
``` 

Assuming a /usr/local/bin type install
```
GOPATH/bin/rita [the executable] -> /usr/local/bin/rita
LICENSE -> /etc/rita/LICENSE
config.yaml -> /etc/rita/config.yaml
tables.yaml -> /etc/rita/tables.yaml
safebrowsing -> /var/lib/rita/safebrowsing
RITALogPath -> /var/lib/rita/log/
``` 
http://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf

**Comment by ethack** [comment]
Fixed with #197
