### ISSUE TITLE
Installer Breaks if INSTALL_PREFIX or CONFIG_PATH

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/rita#192]
If either _INSTALL_PREFIX or _CONFIG_PATH has spaces, the installer will break. Every instance of these variables must be quoted as they are paths that come from the user.

Examples:
Install Prefix: https://github.com/activecm/rita/blob/02b69e10c80518e7c9086fe75bd45e5f904d093e/install.sh#L237

Config Path: https://github.com/activecm/rita/blob/02b69e10c80518e7c9086fe75bd45e5f904d093e/install.sh#L351

**Comment by ethack** [comment]
Fixed with #197
