### ISSUE TITLE
show-scans --ports option doesn't work.

### ISSUE THREAD

**Issue by bekirk** [activecm/rita#207]
The option only prints out a bunch of control characters. 
see sample below:

`Source,Destination,Ports Scanned,Ports
10.11.20.9,10.24.1.15,72,^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^`

**Comment by bekirk** [comment]
I went into my code and fixed this, here is what I changed in the showScans and showScansHuman, hope this gets fixed in the next release.
 functions in the show-scans.go:
```
                if showPorts {
                        portSet := make([]byte, scan.PortCount*3)
                        for i, port := range scan.PortSet {
                                if i != 0 {
                                        portSet = append(portSet, " "...)  //changed line
                                }
                                portSet = strconv.AppendInt(portSet, int64(port), 10)  //changed line
                        }
                        data = append(data, string(portSet))
                }

```

**Comment by bekirk** [comment]
FYI, the code I added gives me the output I wanted but there are still a bunch of null characters (^@) printed to my output, and help cleaning this up would be great!!!

Thank you!

**Comment by Zalgo2462** [comment]
Interesting. First off, thank you for your bug report! The suggested changes look good. I think taking out the allocation size from the make() call will remove the null characters you're seeing. We will get this merged in as soon as possible.

**Comment by bekirk** [comment]
Thank you I tested with your suggested change and it works,  Sorry this is my first go, at golang :)
It now makes sense because there were always 3 times the null characters as there were scanned ports.

**Comment by bekirk** [comment]
Should I close this case as it seems to be fixed?

**Comment by Zalgo2462** [comment]
We'll close it when the pull request is merged.

Thank you!
