### ISSUE TITLE
show-most-visited-urls doesn't work.

### ISSUE THREAD

**Issue by bekirk** [activecm/rita#210]
I am sure I am getting url data however this does not seem to work.  The show-long-urls works and returns data however the show-most-visited-urls returns:

No results were found for Test429.

I have gone into mongodb and ran the following and it returns data so something is not right with the command I think, I sorted from smallest to largest to keep from getting too much data, I just wanted to verify there was data in the database it was looking at:
```
> use Test429
switched to db Test429
> db.urls.find().limit(5).sort( { count: 1 } )
{ "_id" : ObjectId("5ae77f5e7c162f4820881c16"), "ips" : [ "54.84.117.99" ], "length" : NumberLong(64), "count" : 1, "url" : "", "uri" : "/362358.gif?google_gid=CAESEA9bER7Xim56GPb1h7O0Gjk&google_cver=1" }
{ "_id" : ObjectId("5ae77f5e7c162f4820881c17"), "ips" : [ "34.203.131.34" ], "length" : NumberLong(43), "count" : 1, "url" : "", "uri" : "/382666.gif?partner_uid=7847724122311547434" }
{ "_id" : ObjectId("5ae77f5e7c162f4820881c18"), "ips" : [ "54.82.243.230" ], "length" : NumberLong(76), "count" : 1, "url" : "", "uri" : "/384926.gif?served_by=evergreen&partner_uid=2352f79b22d29605c4ec281b5f3106a1" }
{ "_id" : ObjectId("5ae77f5e7c162f4820881c19"), "ips" : [ "54.86.90.181" ], "length" : NumberLong(57), "count" : 1, "url" : "", "uri" : "/395586.gif?partner_uid=a4f11a469dc5e29d2c217103025df853&" }
{ "_id" : ObjectId("5ae77f5e7c162f4820881c1a"), "ips" : [ "54.86.90.181" ], "length" : NumberLong(44), "count" : 1, "url" : "", "uri" : "/397446.gif?partner_uid=eufgwSX2AAoxqI8O6-kK" }
>

``` 

Thank you,
Brian

**Comment by bekirk** [comment]
Let me see if I can simulate this at home, that sample set I worked with was 3gigs compressed plus there is possibly stuff in the urls I might not want to send out our network. How can I check the second thing you asked about. 

I will also see if I can get a smaller sampling of data that behaves the same way. 

Thank you,
Brian

**Comment by Zalgo2462** [comment]
In order to check the second thing, open the ‘mongo’ console or your preferred MongoDB client and run 
‘’‘
use MetaDabase
db.databases.find({name: “Test429”})
‘’’

If the query returns a record, please post it here. In particular, I wonder if the ‘analyzed’ field is set to ‘true’ or ‘false’. 

Thank you for working with us on this.

**Comment by bekirk** [comment]
> use MetaDatabase
switched to db MetaDatabase
> db.databases.find({name:"Test429"})
{ "_id" : ObjectId("5ae76b7c7c162f4820556c9b"), "name" : "Test429",
"analyzed" : true, "import_version" : "v1.0.1", "analyze_version" :
"v1.0.1" }
>

**Comment by bekirk** [comment]
I am really confused.  I just ran the show-long-urls, and
show-most-visited-urls for a 1 hour time windows and they both worked and
are the same results just sorted differently.
So honestly I can use the results from show-long-urls, but it doesn't make
any sense the one works and the other doesn't when I run it for a full
day's worth of data.

**Comment by lisaSW** [comment]
long urls module is depreciated.
