### ISSUE TITLE
Error when analyzing data with RITA

### ISSUE THREAD

**Issue by c0wb0y** [activecm/rita#223]
Prompt the following error when analyzing data with RITA( rita analyze ):
 
 Failed to config: yaml: line 50: did not find expected key

This is part of the configuration file ( /etc/rita/config.yaml )

 39 # The section Bro configures the bro ingestor
 40 Bro:
 41     # Path to a top level directory of log files
 42     ImportDirectory: /var/log/bro/rita/
 43
 44     # Files directly in the ImportDirectory will be imported into a database
 45     # given by DBRoot. Files in a subfolder of ImportDirectory will be imported
 46     # into DBRoot-$SUBFOLDER_NAME.
 47
 48 DBRoot: "RITA"
 49
 50     # This database holds information about the procesed files and databases.
 51     MetaDB: MetaDatabase

 68     SafeBrowsing:
 69         APIKey: "XXXXXXXXXXXXXXXXX-XXXXXX"
 70         Database: /var/lib/rita/safebrowsing

Has anyone encountered the same problem?

**Comment by ethack** [comment]
Whitespace is important in YAML.  I think you just need to indent your `DBRoot: "RITA"` line with 4 spaces to line it up.

If you have trouble getting the spacing right, you can download a fresh copy of the config file and edit with your config options, taking care not to change the spacing at the beginning of the lines.
https://raw.githubusercontent.com/activecm/rita/master/etc/rita.yaml

**Comment by c0wb0y** [comment]
Thank you very much for your answer, my problem has been solved.
