### ISSUE TITLE
Installation of Bro IDS fails

### ISSUE THREAD

**Issue by mahmoodn** [activecm/rita#236]
The installer fails at line 439!

```
# ./install.sh

 _ \ _ _| __ __|  \
   /   |     |   _ \
_|_\ ___|   _| _/  _\  v1.0.2

Brought to you by Active CounterMeasures

[-] In order to run the installer, several basic packages must be installed.
        [-] Updating packages... SUCCESS
        [-] Ensuring git is installed... SUCCESS
        [-] Ensuring curl is installed... SUCCESS
        [-] Ensuring make is installed... SUCCESS
        [-] Ensuring coreutils is installed... SUCCESS
        [-] Ensuring lsb-release is installed... SUCCESS
[-] This installer will:
        [-] Install Bro IDS to /opt/bro
        [-] Install MongoDB
        [-] Install RITA to /usr/local/bin/rita
        [-] Create a runtime directory for RITA in /var/lib/rita
        [-] Create a configuration directory for RITA in /etc/rita
[-] Installing Bro IDS...
[!] Installation FAILED on line 439.

```
That line is `curl -s -L "$3" | apt-key add - > /dev/null 2>&1`
How can I dig  more? Any guess?

**Comment by mahmoodn** [comment]
OK. I removed `> /dev/null 2>&1` and see the following error
```

[-] This installer will:
        [-] Install Bro IDS to /opt/bro
        [-] Install MongoDB
        [-] Install RITA to /usr/local/bin/rita
        [-] Create a runtime directory for RITA in /var/lib/rita
        [-] Create a configuration directory for RITA in /etc/rita
gpg: no valid OpenPGP data found.

[!] Installation FAILED on line 439.

```

**Comment by ethack** [comment]
@mahmoodn Could you please provide the output of this command `lsb_release -a`?

**Comment by mahmoodn** [comment]
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic

**Comment by ethack** [comment]
@mahmoodn I'm sorry to say that we don't officially support Ubuntu 18.04.  It's on our roadmap, but for now your best best is to use Ubuntu 16.04.

Another option you could try is to install Bro manually or find the package for Ubuntu 18.04 and then try running the rita installer again with `sudo ./install.sh --disable-bro`.  I'm not sure if that will work but it could be worth a shot.
