### ISSUE TITLE
RITA should check for new version

### ISSUE THREAD

**Issue by ethack** [activecm/rita#239]
Currently there is nothing in RITA's workflow that would prompt someone to go check if there is an updated version of RITA available. This could lead people to never getting improvements if they don't notice any problems with their version of RITA.

RITA should have a way of checking if there is a new version available on Github and notifying the user. This could be done a number of different ways, but the important part is to make the user aware of the update without disrupting their current workflow.

Here's one possibility:
Modify the config file to have something like `UpdateCheckFrequency` fields with a number of days.  The MetaDatabase could contain something like `lastSuccessfulUpdateCheck` and `latestVersionAvailable` which would contain a date and the latest version number on Github.  

When any rita command is run it should reference the config file to determine if it should reach out to Github and check for an update.  This gives the user the ability to configure the update frequency or disable it (`UpdateCheckFrequency: 0`) if they wish.  It also limits the number of times rita will attempt to make a network connection as in some environments this could introduce a delay or even a network timeout. 

By storing those two values in the MetaDatabase, rita could display a message to the user every time certain commands are run (e.g. `help`, `--help`, `--version`, `import`, `analyze`) that there is an update available.  This should give the user enough notice without interrupting their workflow.

**Comment by zaowen** [comment]
Can I do this?

**Comment by SamuelCarroll** [comment]
@zaowen should be good, please ensure you follow the contributing guidelines at [special](https://github.com/activecm/rita/blob/master/Contributing.md) (focus on [special](https://github.com/activecm/rita/blob/master/Contributing.md#gittiquette-summary))
