### ISSUE TITLE
Import doesn't appear to work

### ISSUE THREAD

**Issue by packetsmacker** [activecm/rita#249]
See the commands below

`rita import 2018-09-19 testing_db`
`[+] Importing /opt/bro/logs/2018-09-19`
	`[-] Finding files to parse`
	`[-] Indexing log entries. This may take a while.`

Checking databases
`/opt/bro/logs# rita show-databases`
`/opt/bro/logs# 
`

From mongo
`> show databases`
`MetaDatabase  0.000GB`
`admin         0.000GB`
`local         0.000GB`

I am not sure what I did wrong but it doesn't appear to be creating any datasets

**Comment by ethack** [comment]
It doesn't look like RITA is finding any files to parse.

Which version of RITA are you running `rita version -v`?

Could you run `ls -l 2018-09-19`?  Are there any `conn`, `http`, or `dns` logs present?
If so could you `cat` or `zcat` the first few lines of one of these logs?

**Comment by packetsmacker** [comment]
Version output
`/opt/bro/logs# rita -v`
`rita version v1.0.2`

Cat works on all the files. I realized the are in json format. Is that the problem?

**Comment by ethack** [comment]
That would be the problem.  If you wanted to switch back to TSV I think you just have to comment out the `@load json-logs` line in the local.bro file.
