### ISSUE TITLE
Change binary install path to /opt/rita/bin/rita

### ISSUE THREAD

**Issue by william-stearns** [activecm/rita#256]

**Comment by ethack** [comment]
My preference is to keep things as they are.  RITA is currently following a widely accepted standard on where to place files.
https://github.com/activecm/rita/issues/191

Do you have any reason for moving it other than that's where AI-Hunter expects it?  I'd rather write the migrations for AI-Hunter to have it look in /usr/local/bin/rita instead.

**Comment by ethack** [comment]
Looks like for consistency we'll want to put a symlink in /usr/local/bin/rita at least.
https://github.com/activecm/ipfix-rita/issues/41#issuecomment-435212467

**Comment by ethack** [comment]
I don't think this is a problem anymore so I'm going to close this issue.
