### ISSUE TITLE
Package Rita as docker instance

### ISSUE THREAD

**Issue by william-stearns** [activecm/rita#257]

**Comment by ethack** [comment]
RITA already has a docker image and suggested compose files.  This issue could use more details and I think the intent here is to have an installer that uses docker images for all components (rita, mongo, bro), but someone fill me in if there's more to it than this.

**Comment by ethack** [comment]
I'm closing this issue unless we have more details or specific need later.  As mentioned, Rita already has a docker image at quay.io/activecm/rita and documentation [here](https://github.com/activecm/rita/blob/master/docs/Docker%20Usage.md).
