### ISSUE TITLE
make install: dep missing dependency 

### ISSUE THREAD

**Issue by bardelch** [activecm/rita#263]
# Problem in Manual Installation.md
```
~/go/src/github.com/activecm/rita$ make install
dep ensure --no-vendor
make: dep: Command not found
Makefile:52: recipe for target 'Gopkg.lock' failed
make: *** [Gopkg.lock] Error 127
```
# Root cause
`go get github.com/activecm/rita`
This appears to have not installed a dependent program 'dep' through go
# Proposed fix
`go get -u github.com/activecm/rita`
`go get -u github.com/golang/dep/cmd/dep`

**Comment by ethack** [comment]
@bardelch Thanks for the bug report.  I just committed a revision that adds dep instructions as well as updates a few other areas.
