### ISSUE TITLE
Create config options to enable/disable analysis modules

### ISSUE THREAD

**Issue by ethack** [activecm/rita#266]

**Comment by ethack** [comment]
Short answer is yes but not yet.  We've talked it over a little and think there's another thing that should be implemented first.  It will make changing the config file easier going forward which will help with this too.  Would you be interested in doing that one first?  If so, I can create an issue with the details and get you some example code from another project.

**Comment by zaowen** [comment]
Sure sounds fun. Tag me on the issue please.

**Comment by ethack** [comment]
The other issue ended up being easier to implement than try to write a spec for, but it's done now. @zaowen Do you want to give this one a shot now?  Here are several things off the top of my head that you'll run across:
- Add an `Enabled` boolean config key under each module's section in the config file.
- When you add the fields in the corresponding config structs, make sure each module has a `default:"true"` tag. This was the piece that was missing before and ensures that older config files won't cause issues with newer versions of RITA.
- The `structure` analysis will need to be done pretty much no matter what but I think the others are fair game to be toggled on/off.  But if you run into any dependency issues just let us know here.
