### ISSUE TITLE
Make rita-bl database configurable

### ISSUE THREAD

**Issue by ethack** [activecm/rita#274]
Rita creates a database for blacklist called `rita-bl`. This is done [here](https://github.com/activecm/rita/blob/48c009a9bc90b03c60932aed11e3d8e720a14248/analysis/blacklist/blacklist.go#L43).  There is also a static config value [here](https://github.com/activecm/rita/blob/48c009a9bc90b03c60932aed11e3d8e720a14248/config/tables.go#L97) that is ignored due to the above hardcoded value.

Both of these should be replaced and an option placed in the rita config file to allow users to customize the name of this database, if present.  The default name could still be `rita-bl`.  I'd call this extremely low priority as this is the first time this has ever come up and I'm doubtful it's an issue that can't be worked around.

**Comment by lisaSW** [comment]
Issue addressed in this pull request: https://github.com/activecm/rita/pull/310
