### ISSUE TITLE
Expand delete database command

### ISSUE THREAD

**Issue by ethack** [activecm/rita#332]
The current delete-database command should be expanded with the following:

- `-a, --all` flag which indicates that all databases should be removed
- `-m, --match` flag which indicates that the given database string should be used as a substring to match against all databases.  (e.g. "2018-12" would match all databases from December like RITA-2018-12-01, RITA-2018-12-02, etc)
- `-r, --regex` flag which indicates that the given database string should be used as a regex to match against all databases.
- `-n, --dry-run` flag which will only print the databases which would be deleted, but not do any deletions and not give any prompts.

The current behavior of the command remains intact:
- Providing a single database name with no arguments will do an exact match on only one database
- Not specifying the `-f, --force` flag will prompt for confirmation on every database, similar to the linux `rm -i` behavior, and including the `--force` flag will delete without prompting, similar to `rm -f`. (The force flag is pending [this pull request](https://github.com/activecm/rita/pull/324))

This feature request is open for suggestions and discussion.

~~These flags could also be applied to the `reset` and `analyze` commands as well.  The behavior is a little bit different.~~
- ~~`reset` has `--all` the default behavior when no database is specified.~~
- ~~`analyze`  has `--all` the default behavior when no database is specified and always assumes `--force` (never prompts)~~

~~So `--force` and `--all` could be added simply for consistency and so that someone leaving those flags in still does the intended behavior. `rita reset --all` and `rita reset` are equivalent, as are `rita analyze --force` and `rita analyze --all`, etc.~~

Edit: the `reset` and `analyze` commands do not exist in the current version anymore.

**Comment by bglebrun** [comment]
It seems like `reset` got rolled into the `delete` commands unless I'm missing it somewhere, this this correct?
