### ISSUE TITLE
Recognize compatible logs (http vs http_eth0)

### ISSUE THREAD

**Issue by ethack** [activecm/rita#333]
In some cases, Bro will generate log files with differences that cause RITA to miss parsing them.  ~~I only have one example right now, but I don't know there aren't others.~~ Security Onion contains a Bro script that makes this change. It only applies to the `http` log [ref](https://github.com/Security-Onion-Solutions/securityonion-bro-scripts/blob/master/add-interface-to-logs.bro)

For http logs the names are normally:
```
http.01:00:00-02:00:00.log.gz
```

But with Security Onion and multiple interfaces the names can come out like this:
```
http_eth0.00:00:00-01:00:00.log.gz
```

The name doesn't make a difference, but in the file header the following line is different and appears to cause RITA to skip the `_eth0` variant.
```
#path   http
```

vs.

```
#path   http_eth0
```

The following code path seems to be the culprit.
- The `path` value gets stored in the `BroHeader` struct [ref](https://github.com/activecm/rita/blob/v2.0.0-beta1/parser/fileparsetypes/fileparsetypes.go#L19)
- This is where the code stores the value [ref](https://github.com/activecm/rita/blob/v2.0.0-beta1/parser/fileparser.go#L71)
- This is where RITA creates the correct file parser based on the `path` value [ref](https://github.com/activecm/rita/blob/v2.0.0-beta1/parser/indexedfile.go#L59)
- And finally, this is the function that simply compares the `path` value against some static strings to determine the type of BroData to use [ref](https://github.com/activecm/rita/blob/v2.0.0-beta1/parser/parsetypes/parsetypes.go#L15)

**Comment by william-stearns** [comment]
Please make the fix portable so that any interface name will be recognized.  The characters between underscore and period can include at least upper and lowercase letters, colon, and digits.

**Comment by ethack** [comment]
Short-term workaround:
```bash
#!/bin/bash

for X in http_eth0.* ; do
        gzcat "$X" | sed -e 's/^\(#path[[:space:]]*\)http_eth0/\1http/' | gzip -9 >`echo $X | sed -e 's/http_eth0\./http./'`.gz
done
```
