### ISSUE TITLE
Add a command line switch to use an alternate local.hjson

### ISSUE THREAD

**Issue by cbrenton-acm** [activecm/rita#35]
The prevalence and first seen features are super useful when monitoring live data. They are far less so, and can skew results if you are working with pcaps. This is also true to under certain conditions with the rare signature value. It would be cool if there was a "-c" switch or similar so that an alternate local.json file could be loaded. This would make it easier to load different config files under different conditions.

**Comment by lisaSW** [comment]
This is already a feature - see top of https://github.com/activecm/rita/blob/main/docs/Configuration.md
