### ISSUE TITLE
v3.0.0-beta2 install file says _RITA_VERSION="v3.0.0-beta1"

### ISSUE THREAD

**Issue by Snarfamundo** [activecm/rita#447]
Hi,
The install.sh script in the Zip file for RITA v3.0.0-beta2 says:
 _RITA_VERSION="v3.0.0-beta1"
should that be _RITA_VERSION="v3.0.0-beta2"?
[install.sh.txt](https://github.com/activecm/rita/files/3048608/install.sh.txt)

**Comment by ethack** [comment]
Thank you for catching that. We are about to do the final v3.0.0 release and I'll be sure to update that before we do.
