### ISSUE TITLE
Sort restriction MongoDB

### ISSUE THREAD

**Issue by sapp50** [activecm/rita#455]
# rita html-report RITA-2019-04-16
[-] Writing: /corelight/logs/testday2/RITA-2019-04-163/RITA-2019-04-16
Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.
Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.

Having issues with this error.  Is there a way to have Rita allow disk use for mongo?

**Comment by ethack** [comment]
That's an issue we'll have to fix in the next release.  Thank you for bringing that up.  If you want to try to fix it here's what you would need:

Anywhere that `.Pipe(...)` is used in RITA will need `.AllowDiskUse()` appended.  [Here's an example](https://github.com/activecm/rita/blob/master/database/db.go#L171).  [Here](https://github.com/activecm/rita/search?q=Pipe%28&unscoped_q=Pipe%28) are a list of places that might need it.  And here are some examples of it in use:
* https://github.com/activecm/rita/blob/master/database/db.go#L171
* https://github.com/activecm/rita/blob/master/parser/fsimporter.go#L846
* https://github.com/activecm/rita/blob/master/parser/fsimporter.go#L870

As far as I can tell, it doesn't hurt to add this anywhere `Pipe()` is used, but it would at least need to go in the places that are causing the issue for you.
