### ISSUE TITLE
Limits added to rita v3.0.x

### ISSUE THREAD

**Issue by bekirk** [activecm/rita#463]
After upgrading to rita-v3.0.x I noticed that  show-long-connections, show-exploded-dns, show-useragents are limited to just the top 1000 results.  Also the field mapping changed in some of the csv outputs.  I would like to be able to override the 1000 result limit with a command-line option, and want to verify all the fields for all the show commands, is there a quick place I can look for that?

I ingest the outputs from these into splunk and need to update my fields to match the output from the show commands.  Also the show-long-connections port:protocol:service field is difficult to ingest is it always 1 or 2 sets of data, separated by whitespace, is the - unknown service, and what is the xmpp,ssl?

I just noticed one line has 3 sets of data in the Port:Protocol:Service field.

> Source IP,Destination IP,Port:Protocol:Service,Duration
192.168.99.107,35.169.5.67,17273:tcp:-,565565
192.168.88.201,74.125.192.125,"5222:tcp:**_xmpp,ssl_**",465551
192.168.88.207,34.236.238.42,0:icmp:-,166008
192.168.88.225,34.228.246.148,443:tcp:ssl,130322
192.168.99.108,20.42.27.104,8883:tcp:ssl,90002.8
192.168.88.201,173.194.208.189,443:udp:-,89271.1
192.168.88.201,209.85.232.127,**_3:icmp:- 19305:udp:- 19302:udp_**:-,61061.7
192.168.88.206,34.236.238.42,0:icmp:-,53693.4
192.168.88.22,74.217.90.199,443:tcp:ssl,41646.4
192.168.88.201,173.194.204.125,"5222:tcp:xmpp,ssl",38244.4
192.168.88.10,52.21.3.59,443:tcp:- 443:tcp:ssl,30815.6
192.168.88.10,52.21.18.219,443:tcp:ssl,30724.9
192.168.88.201,52.39.159.171,443:tcp:ssl,30479.1
192.168.88.201,52.35.71.35,443:tcp:ssl,24238.5
192.168.88.225,52.46.132.58,443:tcp:ssl,23703.1
192.168.88.225,52.46.156.62,443:tcp:ssl,19418.4
192.168.88.201,173.194.207.125,"5222:tcp:xmpp,ssl",14863.8
192.168.88.225,52.46.136.99,443:tcp:ssl,14583.2
192.168.88.225,52.94.240.160,443:tcp:ssl,8683.38
192.168.88.218,199.248.185.84,443:udp:- 443:tcp:ssl,8527.76
192.168.88.209,52.94.235.50,443:tcp:ssl,7183.31

Thank you,
Brian

**Comment by ethack** [comment]
Making those limits a command line option is a good idea.  I'll rename this issue accordingly so we can put that in a future release.

The Port:Protocol:Service field is a little tricky to understand.  I'll call the values there a "tuple".  First, even though long connections is showing a single connection between two systems, that field shows the unique tuples associated with all connections between those two hosts.  Furthermore, that field gets truncated to 5 entries.  So if there are less than 5 entries the long connection listed will be using one of those tuples for its communication.  If there are 5 entries then there is a chance that the tuple used in the long connection is not listed.

As far as the format of each tuple, it is "port:protocol:service".  Multiple tuples are separated by spaces.  The port, protocol, and service values come directly from Bro/Zeek's conn.log.  I can't find a reference for all the service values but [here](https://docs.zeek.org/en/stable/scripts/base/protocols/conn/main.bro.html#type-Conn::Info) is the reference to the log I'm talking about.  If the service entry is empty then it is set to "-" as shown [here](https://github.com/activecm/rita/blob/31d72a728496aa8d88bc07165f10e6ae210d3dbb/parser/fsimporter.go#L359-L364).  As far as `xmpp,ssl` goes, that will have come from the conn.log and while I couldn't find a reference I'd speculate that means Bro believes the connection is XMPP over TLS/SSL.  You may know of XMPP already but for completeness, it is an instant messaging protocol used by a number of [clients](https://xmpp.org/software/clients.html).

Let us know if there are any other fields you have questions on.
