### ISSUE TITLE
Ubuntu version

### ISSUE THREAD

**Issue by phaetom** [activecm/rita#464]
I cannot seem to get RITA installed in Ubuntu Bionic Beaver release (18.04.2 LTS). 
The installer works fine until in passes Bro installation and starts with Mongo DB but stops install without any error. 
From logs it looks to me that the MongoDB version is not correct but i am not sure.

Or do I have to use Ubuntu 16.04 LTS to install RITA.

**Comment by ethack** [comment]
Our installer currently doesn't support Ubuntu 18.04.  You can use the [manual install instructions](https://github.com/activecm/rita/blob/master/docs/Manual%20Installation.md) though if you want to install it on an OS we don't support yet.  It involves installing Bro and Mongo manually.  Rita just needs a binary downloaded, a config file in the right location, and optionally a directory created for logs to write to.  You can also use this to see where the install script failed and then add whatever it missed.
