### ISSUE TITLE
Certificate count missing check if exists

### ISSUE THREAD

**Issue by ethack** [activecm/rita#477]
[This line](https://github.com/activecm/rita/blob/d85e69e1ca417430ab89bae872c30c5e84dd0c25/parser/fsimporter.go#L651) is incrementing the map without a checking if that entry exists first.  It needs to verify that entry exists like was done in [this pull request](https://github.com/activecm/rita/pull/435/files) (and similar to the blocks above the line 651 mentioned above).

**Comment by carrohan** [comment]
@ethack that line on master has changed, and looks like it's properly checking. Does this need to be changed somewhere else?

**Comment by ethack** [comment]
The pull request mentioned fixed this issue. Looks like the issue didn't get closed automatically though.
