### ISSUE TITLE
Import error message is misleading

### ISSUE THREAD

**Issue by ethack** [activecm/rita#491]
When unsuccessfully attempting to import a directory, RITA will give off two different error messages, depending on the case.

The first is if there are Bro logs present, but not any of the types RITA parses. So starting with Bro logs and removing all the ones we parse it gives this:

```bash
rm -rf conn* ssl* x509* http* dns*
# note: there are other logs such as weird, files, notice, known_hosts, etc still present
rita import . test          

	[+] Importing [.]:
	[-] Verifying log files have not been previously parsed into the target dataset ... 
	[!] All files in this directory have already been parsed into database:  test
```

However, when no Bro files are present the message shown is this.

```bash
rm -rf * 
rita import . test

	[+] Importing [.]:

	[!] No compatible log files found
```

The first error message is misleading and I think it should show the second message (No compatible log files found) when RITA runs into the first case of there being Bro logs but nothing that RITA understands.

**Comment by Zalgo2462** [comment]
```
indexedFiles := importer.CollectFileDetails()
// if no compatible files for import were found, exit
if len(indexedFiles) == 0 {
	return cli.NewExitError("No compatible log files found", -1)
}
... 
indexedFiles = removeOldFilesFromIndex(indexedFiles, fs.res.MetaDB, fs.res.Log, fs.res.DB.GetSelectedDB())
// if all files were removed because they've already been imported, handle error
if !(len(indexedFiles) > 0) {
	if fs.rolling {
		fmt.Println("\t[!] All files pertaining to the current chunk entry have already been parsed into database: ", fs.res.DB.GetSelectedDB())
	} else {
		fmt.Println("\t[!] All files in this directory have already been parsed into database: ", fs.res.DB.GetSelectedDB())
	}
	return
}
```

Could you try running your example cases against separate databases? It looks like the only difference in the conditions needed to fire off the two messages are whether there are already processed files in the metadatabase for the given db.

**Comment by ethack** [comment]
https://github.com/activecm/rita/pull/555 seems to have closed this issue as well.
