### ISSUE TITLE
html-report errors with no results

### ISSUE THREAD

**Issue by ethack** [activecm/rita#493]
During an html-report export, if there is an error when writing out any of the modules it will stop writing and not attempt to write any of the following modules.
https://github.com/activecm/rita/blob/v3.0.5/reporting/report.go#L150-L184

But one of the errors that can be encountered is not finding any results for a particular module, which is fairly common and means the report is left incomplete.
https://github.com/activecm/rita/blob/v3.0.5/reporting/report-beacons.go#L30

I suggest these changes:
* If any of the modules produce an error during html-report, print/log the error but keep going.
* Change the module no results errors to not be `cli.NewExitError` since they shouldn't cause an exit.
* Change the module no results errors wording to state what there were no results for. So instead of all saying "No results for db" it should say "No beacon results for db" and "No dns results for db", etc.

**Comment by dustinaevans** [comment]
I am also seeing this. Beacons.html is empty (no content at all), Strobes.html is 404, long-conns.html is 404, useragents.html is 404.
