### ISSUE TITLE
Convert the installer to using the zeek name / zeek scripts

### ISSUE THREAD

**Issue by ethack** [activecm/rita#524]
We've started to run into problems regarding the bro to zeek rename.
https://github.com/activecm/rita/pull/523 is one example.

There's not yet a good list of what needs to be done for this conversion. Here's what we've got so far.
- [ ] https://github.com/activecm/rita/issues/520

**Comment by Zalgo2462** [comment]
Results from grepping for bro throughout RITA.

- `tests/install.bats`: Tests whether bro is installed and configured to start on boot. I'm not sure if this test is still maintained. I never learned how to run this.
- `docs/Manual Installation.md`: Need to update links from bro.org to zeek.org. Need to change Bro to Zeek in multiple places.
- `docs/Bro Install From Source.md`: Need to replace with a guide on installing Zeek from source
- `docs/System Requirements.md`: Uses Bro/Zeek in places. Could be updated to just Zeek.
- `docs/Docker Usage.md`: Need to rename Bro to Zeek
- `install.sh`: 
    - Need to rename Bro to Zeek in several places. 
    - Need to update directory paths. 
    - We should run through a source install of Zeek to correctly detect source Zeek installations in gather_bro/ gather_zeek. 
    - Need to handle migrating users from Bro to Zeek.
    - Need to upgrade JA3 scripts 
    - bro-install/gen-node-cfg.sh: Need to rename bro to zeek in multiple places. Need to update paths.
    - Need to figure out how security onion is handling the zeek transition
- `parser/*.go`: Multiple types, functions, and comments refer to Bro. However, it's likely not necessary to update these.
- `config/static.go`: There is an old config section named Bro where the MetaDB key used to be. It can likely be deleted going forward.
- `commands/import.go`: Change import usage statement.
- `Readme.md`: Multiple references to Bro need to be updated to be Zeek. Some example paths need updating.

**Comment by kaliRegenold** [comment]
Not ready to make a PR, but working on it here: https://github.com/activecm/rita/tree/524-convert-to-zeek
