### ISSUE TITLE
Integration with Corelight appliance

### ISSUE THREAD

**Issue by lawson-kc** [activecm/rita#544]
I'm having a couple of issues integrating RITA with data generated by a Corelight appliance.

**Environment:**
Corelight appliance running the most current production version.  Log files delivered to RITA system via SFTP batch upload.

RITA version 3.1.1 and MongoDB on the same system (install by the provided script)

**Issues**
The Corelight appliance is sending logs to /home/user1/corelight/logs (TSV format).
In that directory, you will see subdirectories for each day:
user1@pocrita:~/corelight/logs$ ls -l
total 140
drwxr-xr-x 2 user1 user1 45056 Feb 25 08:10 2020-02-24
drwxr-xr-x 2 user1 user1 57344 Feb 26 08:10 2020-02-25
drwxr-xr-x 2 user1 user1 36864 Feb 26 21:24 2020-02-26

When I try to do an import to /home/user1/corelight/logs/*, it looks like RITA is processing the data, but I don't see any inserts happening on the mongo DB, and even if I let it run for hours, I get no results with any of the "show" commands.

root@pocrita:~# rita show-beacons corelight1
No results were found for corelight1

Also the RITA import process never terminates on its own.

In the logs, I see several repetitions of the following warnings:
time="2020-02-26T21:50:27Z" level=info msg="the log contains a field with no candidate in the data structure" error="unmatched field in log" missing_field=resp_cc
time="2020-02-26T21:50:27Z" level=info msg="the log contains a field with no candidate in the data structure" error="unmatched field in log" missing_field=ja3s

Not too worried about these.  They are just "info" level messages that I believe are related to some plugins that I have installed to the corelight appliance.  There are no other errors.

So my main concern is that I don't know why I am not seeing any data, or why the import process never terminates.

**Comment by lawson-kc** [comment]
Just wanted to add some information about the errors in the log.  The error for the resp_cc field is in the conn.log.  I suspect that this was added from a plugin but I'm not sure which one.  This is the header information and a couple of events for that log:
#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	proto	service	duration	orig_bytes	resp_bytes	conn_state	local_orig	local_resp	missed_bytes	history	orig_pkts	orig_ip_bytes	resp_pkts	resp_ip_bytes	tunnel_parents	orig_cc	resp_cc
#types	time	string	addr	port	addr	port	enum	string	interval	count	count	string	bool	bool	count	string	count	count	count	count	set[string]	string	string
1582923594.204684	CQWQkz25ThISqhi8L	10.254.7.81	56957	10.104.192.101	389	tcp	-	0.190693	4246	0	SH	T	T	0	SADF10	4658	0	0	-	-	-
1582923568.706586	CDicqN38G822gN3BFk	10.122.65.41	62296	10.1.192.48	912	tcp	-	0.136492	26	26	OTH	T	T	0	DdA	106	2	132	-	-	-
1582923568.658305	CI5VmB3kDFJVRmbyJe	10.254.186.69	58967	10.1.192.48	912	tcp	-	0.000771	1	0	OTH	T	T	0	Da	41	2	80	-	-	-


And the error regarding ja3s field is from the SSL log. This is a field added by the JA3 plugin.
#fields	ts	uid	id.orig_h	id.orig_p	id.resp_h	id.resp_p	version	cipher	curve	server_name	resumed	last_alert	next_protocol	established	cert_chain_fuids	client_cert_chain_fuids	subject	issuer	client_subject	client_issuer	ja3	ja3s
#types	time	string	addr	port	addr	port	string	string	string	string	bool	string	string	bool	vector[string]	vector[string]	string	string	string	string	string	string
1582923598.223595	CAvFw44QLWfVF7os5a	10.144.152.255	62018	10.1.192.48	912	TLSv12	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384	secp384r1	ocws.officeapps.live.com	F	-	-	T	F3YW1H2fR3lkBkeqbd,F3qvLU2U6LhsL3B92k	(empty)	CN=ocws.officeapps.live.com	CN=Microsoft IT TLS CA 5,OU=Microsoft IT,O=Microsoft Corporation,L=Redmond,ST=Washington,C=US	-	ce5f3254611a8c095a3d821d44539877	986571066668055ae9481cb84fda634a
1582923567.459554	C8zfsp2NkXdF21Ela	192.55.52.209	62285	20.190.133.66	443	TLSv12	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384	secp256r1	login.microsoftonline.com	F	-	-	F	Fopk4u3bA6fERoUXo1,FATi8X15FIF2xdKckc	(empty)	-	-	-	-	10ee8d30a5d01c042afd7b2b205facc4	678aeaf909676262acfb913ccb78a126
1582923593.391281	CRGnVsDpmj1mMMz21	10.202.129.91	60324	96.7.91.217	443	-	-	-	cdn.walkme.com	F	-	-	F	-	-	-	-	-	-	3c496cde07cd47b1031428146eebb850	-
1582923597.932690	CbJwDb3CwsHk5RXnAc	10.108.24.29	56370	10.1.192.48	912	TLSv12	TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256	secp256r1	infra-api.newrelic.com	F	-	-	T	F1Fwie2Q71Uh74Eu58,F6jFz92DCGx0bnLjfl	(empty)	CN=*.newrelic.com,O=New Relic\\, Inc.,L=San Francisco,ST=California,C=US	CN=GeoTrust RSA CA 2018,OU=www.digicert.com,O=DigiCert Inc,C=USd3e1de2ca313c6c0a639f69cc3e924a4	303951d4c50efb2e991652225a6f02b1

**Comment by bekirk** [comment]
This is good to know I have Corelight I will upgrade Rita to version 3.1.1
and see if I have the same issue.  I will try this on Monday.

**Comment by lisaSW** [comment]
@lawson-kc  I would be happy to try to work this out with you. We can try to figure out the conn log issues first.
For reference to the field parsing in the conn log that we'll be troubleshooting you can refer [here].(https://github.com/activecm/rita/blob/b04906fd8e470f061db71a2545fe4b34acc717d8/parser/parsetypes/conn.go#L9)
It looks like the orig_cc resp_cc fields are giving you info log errors because, as you can see from the document above, we don't have parsing set up for them. We should still add any missing fields to avoid these errors so I apologize and will be taking care of that. The rest of the fields in the header you posted match the parsing we have set up, so at least we know its not the field names. Would you mind posting the internal subnets section of your config in `/etc/rita/config.yaml`? It must be the file at that location, the one in your rita directory is a backup.

**Comment by lawson-kc** [comment]
@lisaSW Here is the section of the config file you asked for.  This is the default, but appropriate for the network feeds coming into the corelight appliance.
    InternalSubnets:
      - 10.0.0.0/8          # Private-Use Networks  RFC 1918
      - 172.16.0.0/12       # Private-Use Networks  RFC 1918
      - 192.168.0.0/16      # Private-Use Networks  RFC 1918

**Comment by lisaSW** [comment]
You mentioned that rita looks like its processing the logs, do you have a screencap or description of where it gets stuck? Are you able to check if there are any entries or collections created for the database in mongo or are they just empty collections?

**Comment by ethack** [comment]
Closing due to lack of info. Feel free to re-open if this is still an issue.
