### ISSUE TITLE
New Install from SO

### ISSUE THREAD

**Issue by SamyLola** [activecm/rita#556]
I had installed Security Onion with only Zeek and the viewers active. After installing Rita without on top of this with the option not to install Zeek and Bro I tried to use the command to import the zeek logs (rita import /nsm/bro/logs/)  When doing so I get the error no compatible log files found.

**Comment by ethack** [comment]
Try giving rita a directory with the log files directly in it. Also make sure to give a database name e.g `rita import /nsm/bro/logs/2020-03-18 mydatabasename`

**Comment by SamyLola** [comment]
That worked if I wanted a different day can I use the same command with a different date to overwrite it.  Also is there a way to take multiple dates?

**Comment by ethack** [comment]
For a different day you can either import into a different database or you can overwrite the same database with `rita import --delete /nsm/bro/logs/2020-03-18 mydatabasename`

I might be misunderstanding your question about multiple dates. But you can either import them into the same database by just specifying multiple directories like this:
```
rita import /nsm/bro/logs/2020-03-18 /nsm/bro/logs/2020-03-19 mydatabasename
```

If you'd like to automate it to import new data every hour I have updated our documentation to give an example that does this.
https://github.com/activecm/rita/tree/documentation-updates#rolling-datasets

Let us know if that addresses your questions.
