### ISSUE TITLE
RITA can't read JSON format

### ISSUE THREAD

**Issue by muftihatur** [activecm/rita#559]
i think RITA can process JSON format, but when I convert pcap to JSON format by using tshark command, RITA can't import the file. or should I convert it to bro format only?

**Comment by lisaSW** [comment]
@muftihatur you will need to put those pcaps through bro first. RITA can take in both the TSV and  JSON format of bro logs, not raw pcaps.

**Comment by muftihatur** [comment]
oh ok, thanku lisa

**Comment by lisaSW** [comment]
@muftihatur No problem, let me know if you need any other help :)
