### ISSUE TITLE
Certificate Analysis

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/rita#56]
Bro collects x509 data for every certificate it sees. https://www.bro.org/sphinx/scripts/base/init-bare.bro.html#type-X509::Certificate

We can use this data to find new certificates and identify riskier certificate chains.

**Comment by strandjs** [comment]
I think a simple review would be to simply look at the age of the certs.  

Then, alert on anything from Symantec...

**Comment by lisaSW** [comment]
Duplicate of #179 and #406
