### ISSUE TITLE
install.sh script fails on line 679

### ISSUE THREAD

**Issue by ElbowR00m** [activecm/rita#562]
I am attempting to install RITA in an 'air-gapped' Security Onion machine. The Security Onion machine was built with the securityonion-16.04.6.1.iso image. 

The error trips on line 679, right after the prompt stating "[-] Installing MongoDB". It looks like that part of the code is looking for OS version information and then possibly attempting to reach out to the internet to grab some gpg keys?..

If I am correct in this, that means that RITA requires access to the internet and I will not be able to install RITA just by simply having the install.sh file. Is there a workaround for this, or better yet, am I incorrect and something else is wrong?

Thanks in advance.

**Comment by ethack** [comment]
That's correct. The install script requires internet access.

A workaround would be to install all the components manually. RITA itself isn't too hard as all it involves is a binary, a config file, and optionally some default directories. But RITA depends on both Mongo and Zeek. You have Zeek already on Security Onion so what's left is installing Mongo. We don't have offline install instructions but Mongo's documentation might.

Here are the manual installation instructions.
https://github.com/activecm/rita/blob/master/docs/Manual%20Installation.md

**Comment by ElbowR00m** [comment]
@ethack Thanks for the prompt response. I'll take a look out their site and try and figure it all out. If/when I do, I'll be sure to post back.

**Comment by isee2it** [comment]
If I may comment on this. 
I've came across the same issue with Ubuntu 20.04 LTS (this should not matter)
Steps I've tried:
1. Creating and Adding deb to a new /etc/apt/sources.list.d/sources.list 
2. Copy the: cp -f /etc/apt/sources.list to /etc/apt/sources.list.d/sources.list 
Still the issue stays the same. 
I've got two ethernet adapters connectivity. (also on another machine with 1 adapter also does not work).

Please see screenshot: 

![zeek-bro](https://user-images.githubusercontent.com/52869544/82736472-521c6000-9d2a-11ea-9f8a-b6b9113c3c42.png)

**Comment by isee2it** [comment]
I may have figured it out.
What I did:
Removed line 676 -684
Ran the script again.
Came back with an error at line 200
Added -o "$_OS_CODENAME" == "focal" 
Did not work, so check the repository.

It seems this directory is non existant: 
https://download.opensuse.org/repositories/home:/-logan_bhis 

See Attachement ( cleared up the image a bit ) :

![zeek-bro-non-existant](https://user-images.githubusercontent.com/52869544/82737643-bb07d600-9d32-11ea-9161-c4e29eb1a2bb.png)

**Comment by ethack** [comment]
@isee2it I believe you are having a different issue from the original. I think your issue stems from using Ubuntu 20.04. We note in our readme the OS versions the installer supports, but unfortunately we don't support 20.04 yet.

The path you're going down is adding support for 20.04 to the installer. 
https://download.opensuse.org/repositories/home:/logan_bhis:/ exists (the colon at the end is important), but we will be migrating away from this in the next revision. What you'll run into next is that Bro doesn't have any packages ready-made for 20.04. However, Zeek does (after Bro was renamed to Zeek, they also changed the repository locations). We've got a work in progress to update everything to use the new Zeek name and repositories here.
https://github.com/activecm/rita/pull/569
After that we can add support for 20.04 much easier.

To fix your issue, you'll probably want to install Mongo and Zeek manually on Ubuntu 20.04. See the following resources:
- https://github.com/activecm/rita/blob/master/docs/Manual%20Installation.md
- https://software.opensuse.org//download.html?project=security%3Azeek&package=zeek-lts
- https://docs.mongodb.com/v3.6/tutorial/install-mongodb-on-ubuntu/
