### ISSUE TITLE
Multiple bro machine logs

### ISSUE THREAD

**Issue by ysrp4a4** [activecm/rita#565]
Hi,

Is there a way to import logs from different bro machines into rita

**Comment by ethack** [comment]
RITA is fairly flexible in that you can import any number of Bro logs into any number of datasets.

For instance, if you have logs in different folders from two different systems `system1-logs` and `system2-logs` you could import them separately like this:

```
rita import system1-logs system1-dataset
rita import system2-logs system2-dataset
```

Then you can access the different datasets' results like this:

```
rita show-beacons system1-dataset
rita show-beacons system2-dataset
```

Alternatively, if you'd like the logs to end up in the same dataset you can do that as well:

```
rita import system1-logs system2-logs combined-dataset
rita show beacons combined-dataset
```
