### ISSUE TITLE
HTML Report issue

### ISSUE THREAD

**Issue by ysrp4a4** [activecm/rita#568]
For Rolling Datasets I ran 
rita import --rolling /opt/bro/logs/$(date --date='-1 hour' +%Y-%m-%d)/ dataset_name

data parsing happened successfully but when I ran HTML-report for every 1 hour the report generates the same data. There is no difference.

How can I get the HTML report generated for every 1 hour with the latest logs.
How to whitelist the IP or domains in RITA

**Comment by lisaSW** [comment]
The rolling option aggregates the data together over a 24 hour period, removing older hours as it goes. You are unlikely to see much difference when one hour is added in the final results. Are you saying that you would like separate reports on just each hour, not including any other hours, or that you are surprised the results aren't changing much?

**Comment by ysrp4a4** [comment]
Results are not getting changed

**Comment by lisaSW** [comment]
Here are some steps that we can try to narrow down the issue:
- In your yaml config file (`/etc/rita/yaml`) please set the `DefaultConnectionThresh` under the `Beacon` section to `0`
- Make a connection that you know you have not made in the last 24 hours
- Grep for the associated destination IP in the show-beacon results after logs from that time period have been ingested by rita.
Thank you for you patience, let me know how it goes!

**Comment by ethack** [comment]
Closing as there's not enough info. Feel free to re-open.
