### ISSUE TITLE
does rita support centos8

### ISSUE THREAD

**Issue by faizan-tallat** [activecm/rita#576]
i install rita on centos 8 and it install and after that i reboot my centos 8 but even after showing success on every install thing d=rita doesn't appear in my path and not even in /etc/ ??
does rita support centos 8 or not if not which one verison to install ubuntu 18? or ubuntu 20?

**Comment by ethack** [comment]
RITA provides an install script that works on Ubuntu 18.04 LTS, Ubuntu 16.04 LTS, Security Onion, and CentOS 7.

You can install RITA on an unsupported OS (e.g. CentOS 8 or Ubuntu 20.04) in a couple ways. Pick whichever way looks like it would work best for your situation.
- Manually - https://github.com/activecm/rita/blob/master/docs/Manual%20Installation.md
- Using Docker - https://github.com/activecm/rita/blob/master/docs/Docker%20Usage.md
