### ISSUE TITLE
How to forward zeek logs from client machine to a remote syslog for rita analysis

### ISSUE THREAD

**Issue by kazim-shaikh** [activecm/rita#582]
Hello,

I have recently installed Rita for doing threat hunting for SFTP server & Nginx server which is hosted on internet. I want to forward the zeek logs generated on these servers to my remote syslog/ Rita server for rita analysis on beacon.

i tried couple of things but no luck. 
it would be great help If anyone share the syslog settings for forwarding the zeek logs to syslog/rita sercer.
Thank you in  advance
Kazim Shaikh
India

**Comment by ethack** [comment]
We use https://github.com/activecm/zeek-log-transport to transfer zeek logs. See the comments at the top of the script file on how to use it.

Just to be clear RITA doesn't read logs in syslog format. But as long as you transfer the log files that Zeek writes out you'll be fine.

**Comment by kazim-shaikh** [comment]
Thanks a lot @ethack for your prompt reply. Will check & let you know if anything comes up during implementations.

Thanks again
