### ISSUE TITLE
RITA best practice for Beacon Analysis in Squid Web Proxy setup env

### ISSUE THREAD

**Issue by kazim-shaikh** [activecm/rita#583]
Hi @ethack  , I have installed Rita/Mongo in production env on one of my CentOs 7 system . 
I have installed zeek on Squid web proxy server which transport the logs on Rita / Mongo server  & then it is imported with rita &  html is generated for every 24 hours & gets published on Nginx page for analysis .

While analyzing from html page - i am observing tremendous number of beacons every 24 hours. 

1) What is the best practices in filtering this output ? and key areas that need to be looked into ?
2) Since i have installed zeek on squid server directly - i am seeing source IP as squid server & not endpoints IP which are making connection to internet . all servers are in virtual env. i do have access to squid logs to check the endpoint IP which is talking to internet IP but that is time consuming . how can we capture the endpoints IP as source ip for better analysis in squid web proxy env?

**Comment by ethack** [comment]
For filtering beacon results I made a few suggestions in [this comment](https://github.com/activecm/rita/issues/545#issuecomment-601307464).

Unfortunately, we don't have a good solution for dealing with proxies. They break the IP connection and replace the source and/or destination IP address which fundamentally interferes with our analysis as it is based on source/destination IPs. The best of both worlds option would be to use a transparent proxy. Though I understand that in most cases that is not feasible. We are working on a solution that will use endpoint data (e.g. Sysmon) for the analysis, though that is at least a few months out.

**Comment by kazim-shaikh** [comment]
Thanks a lot @ethack  for prompt reply. going through your suggestions made on https://github.com/activecm/rita/issues/545
