### ISSUE TITLE
Running Script from Cron with Rita

### ISSUE THREAD

**Issue by itguysjusttech** [activecm/rita#585]
I have a simple bash script that runs every morning for the previous day that gets all the DNS and Beacons logs. 

The data is added to two text files which are then emailed. The issue occurs when using cron to run the script, it generates the files runs all the commands except inputting the data into the files. The sent email attached files are always empty. The script doesn't have any issues running when done so manually by the user. The script is below, anyone got a potential fix, the permissions are all correct and I've tried using different directories.

```bash
#!/usr/bin/env bash

echo "Testing bash script works"
CurrentDate=$(date -d '-1 day' '+%Y-%m-%d')
echo $CurrentDate
CurrentDay=$(date -d '-1 day' '+%d')
echo $CurrentDay

echo "running rita import"
rita import /nsm/bro/logs/${CurrentDate} dataset${CurrentDay}
echo "running rita show beacons"
rita show-beacons dataset${CurrentDay} -H > /tmp/${CurrentDay}-beacons.txt
echo "running rita show exploded-dns"
rita show-exploded-dns dataset${CurrentDay} -H > /tmp/${CurrentDay}-dns.txt
echo "running email command"
echo "JTG Kibana Logs Files" | mail -s "Kibana Log Files Please Check" {email address here} -A /tmp/${CurrentDay}-beacons.txt -A /tmp/${CurrentDay}-dns.txt

echo "bash script finished"
```

**Comment by ethack** [comment]
One thought is that `rita` might not be in the path in the context cron is run. You could try changing your script to use the absolute path to rita (e.g. `/usr/local/bin/rita`) and see if that helps.

**Comment by itguysjusttech** [comment]
Thanks for the help just to verify im doing this correctly so using the absolute path it would look like the following:

```bash
#!/usr/bin/env bash

echo "Testing bash script works"
CurrentDate=$(date -d '-1 day' '+%Y-%m-%d')
echo $CurrentDate
CurrentDay=$(date -d '-1 day' '+%d')
echo $CurrentDay

echo "running rita import"
/usr/local/bin/rita import /nsm/bro/logs/${CurrentDate} dataset${CurrentDay}
echo "running rita show beacons"
/usr/local/bin/rita show-beacons dataset${CurrentDay} -H > /tmp/${CurrentDay}-beacons.txt
echo "running rita show exploded-dns"
rita show-exploded-dns dataset${CurrentDay} -H > /tmp/${CurrentDay}-dns.txt
echo "running email command"
echo "JTG Kibana Logs Files" | mail -s "Kibana Log Files Please Check" itguys@justtechgroup.com -A /tmp/${CurrentDay}-beacons.txt -A /tmp/${CurrentDay}-dns.txt

echo "bash script finished"
```

**Comment by itguysjusttech** [comment]
the weird part is that rita import works perfectly fine I believe already

**Comment by ethack** [comment]
I would change the first rita command as well to be an absolute path.

If that doesn't fix the problem here is what else I would try:
1. Delete the beacons and dns files in /tmp/ and delete the current dataset (e.g. dataset09)
2. Trigger the cron job to run (change the schedule for the next couple minutes)
3. Verify that the dataset was created in rita and that you can manually run the show-* commands. Verify that /tmp/09-beacons.txt and /tmp/09-dns.txt exist and have the results inside them (or whatever their names happen to be).

What you find will give more hints on where to look for the problem.

Another test you can do is use this script instead and see if it successfully emails two attachments with contents. This test completely removes rita so you can validate that everything else is working correctly.

```
#!/usr/bin/env bash

echo "Testing bash script works"
CurrentDate=$(date -d '-1 day' '+%Y-%m-%d')
echo $CurrentDate
CurrentDay=$(date -d '-1 day' '+%d')
echo $CurrentDay

echo "running rita show beacons"
echo "beacons file contents" > /tmp/${CurrentDay}-beacons.txt
echo "running rita show exploded-dns"
echo "dns file contents" > /tmp/${CurrentDay}-dns.txt
echo "running email command"
echo "JTG Kibana Logs Files" | mail -s "Kibana Log Files Please Check" itguys@justtechgroup.com -A /tmp/${CurrentDay}-beacons.txt -A /tmp/${CurrentDay}-dns.txt

echo "bash script finished"
```

**Comment by The1WhoPrtNocks** [comment]
Hi,
I am having a simular issue however I can not get the import to run using cron.
I have cahnged my script to create a new dataset each time to confirm, script below.
```
#!/bin/bash  
PATH="INSERT PATH ENVIRONEMNTAL VARIABLES HERE"  
NOW=$(date -d "yesterday" '+%Y-%m-%d')  
/usr/local/bin/rita import --rolling --numchunks 7 /home/luke/zeek_logs/$NOW/ $NOW
```

**Comment by ethack** [comment]
@The1WhoPrtNocks so your script is triggering but the database never shows up? Can you check the rita logs and see if that gives you any clues? [`/var/lib/rita/logs/`](https://github.com/activecm/rita/blob/master/etc/rita.yaml#L41) is the default log location.

**Comment by The1WhoPrtNocks** [comment]
There is nothing in the logs there, either for the normal job that should run at 02:00 , or the test i just set to run at 17:17.
There is a log there though for when i manually completed an import using the same bash script cron is calling.

**Comment by ethack** [comment]
My first thought is a permissions issue. I would try `chmod 777 /var/lib/rita/logs/ && chmod 666 /var/lib/rita/logs/*`to make sure that the log files can be written by any user.

If it is a permission issue then I suspect that the user the cron script runs as doesn't have read permission to `/home/luke/zeek_logs/`. The rita log file should hopefully tell if that's the issue or not.

You could also try setting your cron job to run as `luke` (assuming that's the user where it works to run it manually).

**Comment by The1WhoPrtNocks** [comment]
Thanks for taking a look at this, I have tried to go through all the "gotchas" why cron jobs, however still having this issue.

I altered the permissions on the log file as suggested.
confirmed the job triggered in syslog.
Nothing new logged to /var/lib/rita/logs/2020-10-06.log
the cron job is set to run under the same user context as when run manually (in this case the luke user)

**Comment by The1WhoPrtNocks** [comment]
Also I appreciate at the end of the day this is one command.
Just looking so that ideally tier 1 engineers can start there shift in the morning and jump straight to analysis.

**Comment by ethack** [comment]
Closing old issue.
