### ISSUE TITLE
rita show-beacons not displaying anything

### ISSUE THREAD

**Issue by obaidrahman2020** [activecm/rita#588]
So I just got rita setup on Ubuntu 18.04, and i imported my zeek logs to rita. Zeek is generating logs but my rita show-beacons is not displaying anything.
![image](https://user-images.githubusercontent.com/65261110/93009788-0dc00480-f553-11ea-800d-0fe283aaf599.png)
![image](https://user-images.githubusercontent.com/65261110/93009801-2e885a00-f553-11ea-878f-57db212c7a9c.png)
![image](https://user-images.githubusercontent.com/65261110/93009806-524ba000-f553-11ea-88a5-0aa8e5f07f7d.png)

My internal subnet is in 192.168.100.0/24 subnet and I have edited the /etc/rita/config.yaml file accordingly
![image](https://user-images.githubusercontent.com/65261110/93009914-588e4c00-f554-11ea-959b-63d70c579ee0.png)

I am not sure what I am doing wrong here, please can someone guide me.

**Comment by ethack** [comment]
Beacon detection requires the conn.log. In your first screenshot I don't see the conn.log parsing but I do see http and ssl. As far as I know it's not possible to have http or ssl logs without the conn log so I'm not sure what's going on there. Can you verify you have a conn.log file and there are log entries in it? Then try the import again.

**Comment by obaidrahman2020** [comment]
Thanks, I think it was because my logs only had communication between devices on my local subnet, since this is  a test environment.
 

    On Sunday, September 13, 2020, 07:38:14 p.m. EDT, ethack <notifications@github.com> wrote:  
 
 


Beacon detection requires the conn.log. In your first screenshot I don't see the conn.log parsing but I do see http and ssl. As far as I know it's not possible to have http or ssl logs without the conn log so I'm not sure what's going on there. Can you verify you have a conn.log file and there are log entries in it? Then try the import again.
