### ISSUE TITLE
Add Date/Time Stamp

### ISSUE THREAD

**Issue by Nyhmesis** [activecm/rita#594]
Would it be possible to add a date/time stamp of when the HTML report was ran to the navigation bar on the top of the index.html file? Maybe next to User Agents on the far right or something. There's been a few times where we review the data and didn't realize that a new report failed to generate.

**Comment by ethack** [comment]
This should be straightforward and would be a great first issue if anyone is looking to contribute. I'd suggest pulling `ts_range.max` out of the metadatabase and converting the Unix timestamp to a human readable date and displaying.

https://github.com/activecm/rita/blob/master/database/meta.go#L49

**Comment by edwmorgan** [comment]
If no one has addressed this issue, I'd like to work on it!
