### ISSUE TITLE
Move --config to a global option

### ISSUE THREAD

**Issue by ethack** [activecm/rita#595]
So instead of having to do `rita import --config etc/rita.yaml ...` we would do `rita --config etc/rita.yaml import ...`. This makes it easier to modify most commands since `--config` is less likely to change than the rita subcommand. It also makes it possible to create aliases like:
- `alias rita1=rita --config /etc/rita/config1.yaml`
- `alias rita2=rita --config /etc/rita/config2.yaml`

Where currently this would be impossible with an alias and would need a custom shell function instead.

**Comment by vivek-26** [comment]
Hi @ethack, I have raised a PR for this issue. Please have a look.
