### ISSUE TITLE
Disable malwaredomains threat intel feed

### ISSUE THREAD

**Issue by ethack** [activecm/rita#642]
This feed is no longer available and the default config should be changed to disable it until it is fully removed from [rita-bl](https://github.com/activecm/rita/blob/master/config/static.go#L78).

- https://github.com/activecm/rita/blob/4a4b6394a6fb2619ba91e0112e94a54f0653808a/etc/rita.yaml#L111
- https://github.com/activecm/rita/blob/4a4b6394a6fb2619ba91e0112e94a54f0653808a/config/static.go#L78

https://github.com/activecm/rita-bl/issues/10

**Comment by san-coding** [comment]
Thanks, I do need some sample week logs

**Comment by san-coding** [comment]
Will setting `MalwareDomains.com: false`
https://github.com/activecm/rita/blob/4a4b6394a6fb2619ba91e0112e94a54f0653808a/etc/rita.yaml#L111

And setting  `UseDNSBH          bool     yaml:"MalwareDomains.com" default:"false"` fix the issue


https://github.com/activecm/rita/blob/4a4b6394a6fb2619ba91e0112e94a54f0653808a/config/static.go#L78

**Comment by Andre053** [comment]
Please close this as it appears to have been completed in a separate issue.
