### ISSUE TITLE
Installation FAILED on line 701

### ISSUE THREAD

**Issue by joshjtd7** [activecm/rita#646]
Fresh install of Ubuntu 18.04.5 LTS .  Successfully installs the basic packages.  As soon as it gets past that, it errors.

Thank you in advance for the assistance.

**Comment by Zalgo2462** [comment]
Hello, could you please post the full output you received when running the installation script?

**Comment by joshjtd7** [comment]
> Hello, could you please post the full output you received when running the installation script?
> 
> Line 701 downloads and registers an `apt` repository signing key. This is used to install the repositories for Zeek and MongoDB.
> 
> https://github.com/activecm/rita/blob/5895fc48f341bc2a0741ce3d77f899f83fd1d353/install.sh#L701

 _ \ _ _| __ __|  \
   /   |     |   _ \
_|_\ ___|   _| _/  _\  v4.2.0

Brought to you by Active CounterMeasures

[-] In order to run the installer, several basic packages must be installed. 
	[-] Updating packages... SUCCESS
	[-] Ensuring curl is installed... SUCCESS
	[-] Ensuring coreutils is installed... SUCCESS
	[-] Ensuring lsb-release is installed... SUCCESS
	[-] Ensuring yum-utils is installed... SUCCESS
[-] This installer will: 
	[-] Install Zeek IDS to /opt/zeek 
	[-] Install MongoDB 
	[-] Install RITA to /usr/local/bin/rita 
	[-] Create a runtime directory for RITA in /var/lib/rita 
	[-] Create a configuration directory for RITA in /etc/rita 
[-] Installing Zeek IDS...
[!] Installation FAILED on line 701.

**Comment by Zalgo2462** [comment]
![image](https://user-images.githubusercontent.com/761220/121457793-7e227780-c965-11eb-9419-49af13cdf59d.png)
It seems there is likely an issue with the Zeek repository.

Running `./install.sh --disable-zeek` will likely work around the issue if you do not need to install Zeek.

However, if you do need to install Zeek, please take a look at https://github.com/activecm/docker-zeek while we look into this further.

**Comment by Zalgo2462** [comment]
Today, I was able to install zeek and the rita install script succeeded on a fresh install of Ubuntu 18.0.4.5.

Please try running the installer again and let us know how it goes as it seems the repository problems have likely been fixed.

**Comment by ethack** [comment]
Closing this as stale. This was likely just a temporary issue with the Zeek's Opensuse repository service.
