### ISSUE TITLE
Investigate opening up zeek logs onto a tmpfs-mounted directory for import performance

### ISSUE THREAD

**Issue by william-stearns** [activecm/rita#658]
At the point where rita opens up the log files for a given day, it has to create temporary files on disk that are the opened log files.  These could be placed on a "tmpfs" volume, similar to a ramdisk except a ramdisk unconditionally takes all the ram it's allocated and doesn't release it; a tmpfs mount only grabs ram from the system when a new file shows up, and that ram is released when the file is deleted.  It can be a major performance boost to the system in that one essentially doesn't need to write the opened files to HDD or SDD at all.  (Note, content in a tmpfs volume can get pushed out to swap if memory gets tight; in this case some disk bandwidth is used, but this is less common.)

The concept to test is this: find the directory into which the log files are being opened, and put in (*) a line in /etc/fstab that mounts a tmpfs volume there.  Say this is /opt/zeek/tmp/ ; we'd create a line in /etc/fstab like:

tmpfs						/opt/zeek/tmp		tmpfs	defaults,size=8192G	0 0

That would mount the volume at boot time, and the ram would only be used when these tmp files are needed for import, and released otherwise.

The "8192G" needs to strictly less than the total amount of physical ram + swap, and at a practical level should be <= 1/2 physical ram.  (One additional thing to check - does tmpfs have a maximum?)  

For investigation: does this have a positive difference in import speed?  My guess is that since we avoid a large quantity of writes it will have a positive effect on both HDD and SSD media.

**Comment by william-stearns** [comment]
Additional consideration: if use a hard-coded tmpfs tmp dir on the host for both native (non-docker) and docker packages we'll need to add a docker mount to map the internal directory to the external actually-tmpfs-mounted directory.

**Comment by william-stearns** [comment]
The addition to /etc/fstab will have to be done as root/under sudo , so if we can find a fixed location into which the tmpfs volume can be mounted we may want to do this in the installer.  (Note, check to make sure we don't already have a line for /opt/zeek/tmp there.)

**Comment by william-stearns** [comment]
Ideally we could start unzipping more files while previous files are being imported.... :-)

**Comment by ethack** [comment]
I could be misunderstanding, but I don't think there are any temp files on disk. Rita uses Go's [`compress/gzip`](https://pkg.go.dev/compress/gzip#NewReader) library to read the gzip logs. To the best of my knowledge, this decompresses files in memory already.

https://github.com/activecm/rita/blob/bd06824fbe83f0994f37452f1e5f9f399e894dc9/parser/fileparser.go#L77

Rita never explicitly writes out uncompressed temp files. It's possible the library does but I don't think it's necessary and I don't see anything that indicates it does after lightly perusing the library source code.

**Comment by Zalgo2462** [comment]
Using the system gzip and reading stdout into RAM effectively accomplishes what this investigation set out to accomplish.
