### ISSUE TITLE
Dash-H does not appear to be documented in "rita help" output

### ISSUE THREAD

**Issue by william-stearns** [activecm/rita#701]

**Comment by ethack** [comment]
This is a nuance of many argument parsing libraries. The `-H|--human-readable` option is not a global flag but only applies to specific commands (e.g. `show-*`). You can see it documented in the help message for any of those where it is supported.

```
$ rita show-beacons -h | grep -- -H
   --human-readable, -H                  Print a report instead of csv

$ rita show-exploded-dns -h | grep -- -H
   --human-readable, -H                  Print a report instead of csv
```
