### ISSUE TITLE
Clean Uninstall

### ISSUE THREAD

**Issue by vitick** [activecm/rita#703]
Hi, 

I inherited a collection of RITA boxes and during some troubleshooting accidentally installed it on a device that did not need it. Is there an uninstall script to remove RITA and all dependencies cleanly, or would that be a manual process? Newbie here, just learning the ropes.

Thanks.

**Comment by ethack** [comment]
I don't think there's an uninstall script or step-by-step instructions. 

RITA itself only puts files in a few places: `/usr/local/bin/rita`, `/etc/rita/`, and `/var/lib/rita/`. You can just directly delete all those.

If you need to uninstall Mongo and Zeek as well then I don't have great instructions there. You can get part-way there by just running the `apt` or `yum` uninstall command for your OS. `zeek-lts securityonion-bro` and `mongodb-org mongodb-org-mongos mongodb-org-server mongodb-org-shell mongodb-org-tools` are the package names. 
(You can find these by searching the [`install.sh`](https://github.com/activecm/rita/blob/master/install.sh) script for `__install_packages`.

The only pieces remaining would be the custom repos for Zeek and Mongo in your package manager. You can probably leave these alone. But if you want to remove them on Debian/Ubuntu those files are in `/etc/apt/sources.list.d/`. I'm not sure where they are on Fedora/CentOS.

**Comment by vitick** [comment]
Appreciate the pointers! Looks like everything cleaned up well.
