### ISSUE TITLE
Installing RITA with installer

### ISSUE THREAD

**Issue by jrpayne30040** [activecm/rita#715]
I downloaded and ran the RITA installer on Ubuntu Server 18.04. The process apparently got to Installing Zeek IDS and the next message is Installation FAILED on line 772. I can usually work through these things myself but I really do not have any idea where to start looking for the issue here. Can anyone point me in the right direction on this issue?

Jimmy Payne

**Comment by idbran** [comment]
I have encountered a similar issue on CentOS 7.9
Error: manager terminated immediately after starting; check output with "diag"

[!] Installation FAILED on line 353.

**Comment by idbran** [comment]
I was able to get past this error by removing all references to an old Bro install and the Zeek packages installed by RITA using `rpm -e`.
I then installed Zeek using the OS package manager and then ran the RITA installation script and it worked.

**Comment by jrpayne30040** [comment]
I was able to figure that my issue was a firewall issue. The particular line that the error was being thrown at was a command to go out to the internet and grab a package. Apparently, that address was being blocked due to its geographical location. I granted temporary access for that box and the installer completed.
