### ISSUE TITLE
Fix/ Update Resources for Running RITA with Docker

### ISSUE THREAD

**Issue by Zalgo2462** [activecm/rita#730]
As seen in #729, Go will no longer prioritize the DNS link provided by Docker over the `/hosts` file generated inside the container by Docker. This means that we can no longer link the database container to the RITA container using the name `localhost`. As a result, we can no longer use the stock RITA config file when running RITA with Docker. The `ConnectionString` needs to be set to `db_1` or `rita_db_1` rather than `localhost`. 

We should set a name for the db container in the docker-compose file. Additionally, we should upload a ready-to-go configuration file for running RITA with docker. Finally, we should update the documentation to make it easier to run RITA under Docker.

**Comment by ethack** [comment]
I think the proper connection string would be `mongodb://db:27017`. Using the service name (`db` in this case) in docker-compose files is the best practice and should work in all cases AFAIK. The container name isn't fully deterministic so any attempt to use it directly will hit edge cases where people don't use a `rita` parent directory, are running multiple copies at the same time, etc.

**Comment by Zalgo2462** [comment]
We will need to create a second copy of the rita config file that links to the db container instead of localhost. Then, we will need to update the docker usage docs to point users to that copy of the config file.
