### ISSUE TITLE
help with docker-compose

### ISSUE THREAD

**Issue by kyleEeeEEeeee** [activecm/rita#754]
Hello, I'm attempting to run RITA through docker compose and am getting the following error...

[xxxxxx]$ docker-compose run --rm rita import /home/xxxxxx/logs/* test
Creating network "xxxxxx_default" with the default driver
Creating volume "xxxxxx_db" with default driver
Creating xxxxxx_db_1 ... done
Creating xxxxxx_rita_run ... done
Failed to connect to database: no reachable servers

Can you please tell me what I'm missing?  I have done the export CONFIG and LOGS, and I just copied and pasted the docker-compose.yaml from the github.  Thanks in advance!

**Comment by kyleEeeEEeeee** [comment]
that worked, thanks!  Do you have any suggestions on making the alias?  I couldn't get it to work running the alias command (rita-db-1 > localhost and visa versa) when I changed the config file back to localhost.

**Comment by ethack** [comment]
It doesn't look like using `localhost` will work anymore. 
https://github.com/activecm/rita/issues/730#issue-1184158011
The solution we'll likely go with is shipping a different default config file in the docker container.

**Comment by djlloy1** [comment]
I got Failed to connect to database: no reachable servers

Noticed that my mongodb container got dropped onto network bridge : rita_default  whilst my rita container got dropped on to bridge : default  so 2 couldn't talk..    so worth quickly checking your containers with a 

docker inspect <container>  

and look under ...Networks to make sure they are on the same network  :D   (only works if containers are running.. so need to be quick before rita exits) so slip a cheeky -d (detached)

I solved this by running rita container with docker run --network=rita_default  --rm -it -v .......  

Really impressed with the results!  Cheet sheet is very helpful as well!

**Comment by Zalgo2462** [comment]
Closing this issue in favor of #730 since it looks like everyone was able to get MongoDB, RITA, and docker-compose to work together.
