### ISSUE TITLE
Security Onion 2.3.180

### ISSUE THREAD

**Issue by ng1991** [activecm/rita#766]
Hi,

I have just installed this using the guide on the security onion website (https://docs.securityonion.net/en/2.3/rita.html) 

I have managed to get it installed and can manually create datasets and reports and look at the data, but I am not sure how this integrates with SO. I have followed the following, https://docs.securityonion.net/en/2.3/other-supported-logs.html#example-rita, but the csv files are not created on the nsm directory, and I can't actually see why they would from the setup. I presume I am missing a step but can't see what that would be.

 This is installed on my forwarder node

**Comment by ng1991** [comment]
Hi just adding to this I have now created the CSV files into the rita directory by running rhe below:

rita import --rolling /nsm/zeek/logs/current $HOSTNAME
rita show-open-connections $HOSTNAME > /nsm/rita/open-connections.csv
rita show-beacons $HOSTNAME > /nsm/rita/beacons.csv
rita show-exploded-dns $HOSTNAME > /nsm/rita/exploded-dns.csv
rita show-long-connections $HOSTNAME > /nsm/rita/long-connections.csv

I can see in the filebeat.yml on the minions that the data is defined but it is still not ingested into SO GUI
![image](https://user-images.githubusercontent.com/115169428/206429137-be77c9d5-2fe2-4282-9875-cf34e75d0fb2.png)

Does anyone have any ideas would be much appreciated

**Comment by 0nnyx** [comment]
Cause of your problem : Rita devs changed the csv fields since 4.6.0 while SecurityOnion template remained the same. Problem should be resolved in SO 2.3.200

**Comment by ng1991** [comment]
Hi for anybody else with this issue I also raised a discussion with SO:

https://github.com/Security-Onion-Solutions/securityonion/discussions/9480

The issue can be resolved by adding the updated config to your SO setup on the manager
