### ISSUE TITLE
Rita not loading latest logs

### ISSUE THREAD

**Issue by OrangeLightning219** [activecm/rita#775]
Hi.
I'm trying to use the rolling set feature to analyze zeek logs periodically. The issue is that rita is not loading the latest logs if the files are too big.  From what I found in the source code it looks like rita decides wheter to load the file or not based on the hash of the first 15k bytes of the file. I find this very weird because for example the dns.log gets bigger than 15k after visiting 2-3 websites.

Steps to reproduce te problem:
* run zeek - `zeekctl deploy`
* open up a browser and visit a few websites to make the dns.log bigger than 15k
* import the logs to rita - `rita import --rolling /opt/zeek/logs/current test-db`
* visit a few more websites to add new data to the dns.log
* import the logs to rita again - `rita import --rolling /opt/zeek/logs/current test-db`

After these steps the data gathered in step 4 won't be imported.

Is there a way to work around this? Somthing like an option to force load the logs?

**Comment by ethack** [comment]
Rita isn't designed to import the current open logs into a rolling dataset. What works well is to import logs into rita after they have been rotated and closed out (e.g. every hour). If you want to have the current logs analyzed, I'd recommend putting those in a different, non-rolling dataset. You can use `rita import --delete` to automatically delete and re-import the current data if you want to do it more frequently than every hour.

I don't believe this has been tested, but running `rita import --rolling /opt/zeek/logs/current test-db || rita import --rolling --delete /opt/zeek/logs/current test-db` may actually give you what you want assuming:
- The first command exits with an error code stating the files have already been imported. I'm not 100% sure this is the case. Even if it doesn't, you could come up with a short script that would grep the output and then conditionally run the second command.
- The `--delete` flag in the second command states it will replace the most recent chunk in a rolling dataset. I don't believe this has been heavily utilized and I don't have any experience with this scenario, but it seems straightforward.
