### ISSUE TITLE
Combine argument error handling in show-dns-fqdn-ips to handle less than 2 args

### ISSUE THREAD

**Issue by kirkhauck** [activecm/rita#813]
Right now, the command's logic will tell the user to specify a database if they don't supply any arguments and to specify an FQDN if the user only has one argument. However, this can be potentially confusing if the user enters only an IP address because the command will see there is only one argument then tell them to enter an IP address. Adjust the logic to prompt the user to enter a database and an IP address if they provide fewer than two arguments to avoid confusion.

**Comment by Zalgo2462** [comment]
Closed by #814
