### ISSUE TITLE
Scanning module improvement

### ISSUE THREAD

**Issue by lawrencehoffman** [activecm/rita#9]
*For version: 0.9.2*

The scanning module is quite broken. It will find port scanning, but the output is very noisy. Specifically anything that does NAT or Proxy etc. will come up as a port scan. The module needs to be rewritten to use something like the port popularity list from [nmap](https://svn.nmap.org/nmap/nmap-services) to score the likelihood that a machine which is seen accessing multiple ports on another machine is actually scanning.

**Comment by Zalgo2462** [comment]
Conn state may be used to find specific types of scans (syn, xmas, etc) https://www.bro.org/sphinx/scripts/base/protocols/conn/main.bro.html

**Comment by lisaSW** [comment]
scans module has been depreciated.
